### PR TITLE
Recognise more testing frameworks

### PR DESCRIPTION
**Pull request by max-schaefer**
I've only added tests for one of them, which is part of the standard library. The others might be good test cases for the stubber.

### CODE REVIEW

**Comment by max-schaefer** [comment]
> Should I try adding tests using the stubber in a different PR?

Yes, please, but that doesn't need to go into 1.24.

**Comment by intrigus-lgtm** [comment]
What's "the stubber"?

**Comment by max-schaefer** [comment]
It's something @sauyon has been working on; watch this space.

**Comment by intrigus-lgtm** [comment]
Well I guess then I don't have to try to write one :) 
Maybe I'll write one anyway to learn more Go :D

**Pull request merged**
