### PR TITLE
Cleanup: use TypeSwitchStmt.getAssign, not a raw child accessor

### PR DESCRIPTION
**Pull request by smowton**
Trivial cleanup I noticed while researching our control-flow analysis

### CODE REVIEW

**Comment by max-schaefer** [comment]
Oh, hm, those test failures are interesting. Note that `getAssign()` has result type `SimpleAssignStmt`, so this rewriting is not semantics-preserving for cases where the first child statement is _not_ an assignment. (It can just be an expression statement.)

**Comment by smowton** [comment]
Ah sure, forgot about QL's silent downcasting ways :) Think it's worth adding / using `Stmt getTestStmt` which could be an ExprStmt or SimpleAssignStmt?

**Comment by max-schaefer** [comment]
Sure, that sounds like a good idea.

**Comment by max-schaefer** [comment]
I believe this has been superseded by https://github.com/github/codeql-go/pull/226.

**Pull request closed without merging**
