### PR TITLE
Add sample DB-related queries

### PR DESCRIPTION
**Pull request by sauyon**
Very barebones qhelps and tests since these are likely to live in experimental for some time anyway.

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Review by sampart — COMMENTED** [review]
This looks good to my untrained eye; thank you so much for putting this together. Once it's merged, I'll chat to you about what we should tell users about how to make use of these queries.

Would you be happy to update this PR to also "promote" the existing `ql/examples/snippets/deferinloop.ql` to be an experimental query? That way, all 3 queries mentioned in the blog post can be used in the same way.

**Comment by sauyon** [comment]
I've done so.

**Review by sampart — APPROVED** [review]
Thank you!

**Comment by smowton** [comment]
@sauyon tests failing

**Comment by sauyon** [comment]
Forgot to push the `.expected` file.

**Comment by smowton** [comment]
@sampart this is merged

**Pull request merged**
