### PR TITLE
Port recent data-flow improvements

### PR DESCRIPTION
**Pull request by max-schaefer**
https://github.com/Semmle/ql/pull/3020 and https://github.com/Semmle/ql/pull/3021

[Evaluation](https://git.semmle.com/max/dist-compare-reports/blob/master/go/update-data-flow/report.md) claims a slight speedup, but this is perhaps to be taken with a grain of salt:  a previous evaluation showed a minor overall slowdown.

### CODE REVIEW

**Comment by max-schaefer** [comment]
Tests fixed by committing test output changes, which look benign.

**Comment by sauyon** [comment]
Would it be possible to quickly explain type pruning, and what the expected output change actually means?

My rudimentary understanding is that flow would be pruned when something went through a nil valued type or similar, and this was overriding custom taint steps. The expected output changes here because the type is reset to the original type for all additional taint steps to work around this.

Does that sound about right?

**Comment by max-schaefer** [comment]
Sounds plausible, but I haven't looked at it in detail yet. No rush to merge this, we can leave it open for now until we have more clarity on this.

**Comment by max-schaefer** [comment]
Thanks for taking a look.

This needs a rebase, and while I'm at it I might as well pull in changes from https://github.com/github/codeql/pull/3110 and https://github.com/github/codeql/pull/3312 and do another evaluation.

I'll demote this PR to a draft in the meantime.

**Comment by max-schaefer** [comment]
I've ported over changes from the PRs mentioned above, and [redone](https://git.semmle.com/max/dist-compare-reports/blob/master/go/update-data-flow/report.md) the evaluation.

The good news is that performance is unchanged and we haven't lost any results.

The bad news is that there are a fair number of new results, and they don't look too convincing. I've examined a few of them in detail, and in every case the path itself seems fine, so the problem is really with the query, not the libraries (usually it's missed sanitisers and overly liberal sinks).

I would propose that we merge this PR and then make issues for the dubious new results.

**Comment by sauyon** [comment]
Ok, that sounds sensible. Should I make the issues?

**Comment by max-schaefer** [comment]
Sure, if you have time, that would be great. I can also make a few if you'd like me to.

Come to think of it, this PR now needs a change note; let me write one real quick...

**Comment by max-schaefer** [comment]
Change note added.

**Pull request merged**
