### PR TITLE
Add and move around a few convenience predicates

### PR DESCRIPTION
**Pull request by max-schaefer**
In some cases I've moved predicates onto their superclass to make them more discoverable and avoid casts, in other cases the information computed by the predicate was already there, but not conveniently exposed.

### CODE REVIEW

**Comment by max-schaefer** [comment]
Changes like these are conceptually simple but surprisingly fiddly due to prescriptive typing, so I think I'll run an evaluation over the weekend just to get some extra confidence that I didn't accidentally make some predicate empty.

**Comment by max-schaefer** [comment]
Evaluation came back clean.

**Review by sauyon — APPROVED** [review]
LGTM. Should we have tests for these?

**Comment by max-schaefer** [comment]
Sure; let me look into that.

**Comment by max-schaefer** [comment]
I've added tests for `Function.getResult(i)`, which is the main new predicate being added.

**Review by sauyon — APPROVED** [review]

**Pull request merged**
