### PR TITLE
Add codemill spec for clevergo

### PR DESCRIPTION
**Pull request by gagliardetto**

### CODE REVIEW

**Review by smowton — APPROVED** [review]

**Comment by smowton** [comment]
Actually this might be better side-by-side with `CleverGo.qll` (and include a remark in the `qll` file that it is generated from this file)

**Comment by gagliardetto** [comment]
Moved

**Review by smowton — APPROVED** [review]

**Comment by gagliardetto** [comment]
As far as I can see, automerge won't work retroactively (i.e. the approval and successful build need to happen **after** the enabling of automerge).

**Comment by sauyon** [comment]
(I believe it was requiring you to merge or rebase main into the PR)

**Comment by gagliardetto** [comment]
> (I believe it was requiring you to merge or rebase main into the PR)

Makes sense

**Pull request merged**
