### PR TITLE
Go 1.14 support

### PR DESCRIPTION
**Pull request by sauyon**
Add tests and model the one relevant API change.

### CODE REVIEW

**Comment by sauyon** [comment]
I've added a few tests involving embedded interfaces which don't seem to work correctly, I've filed [this issue](https://github.com/github/codeql-go-team/issues/56) (internal link) for it.

**Comment by sauyon** [comment]
Ah, the builds are failing because of 1.14 changes to the vendoring process, it seems. I'll update the dependencies and run a dist-compare.

**Comment by max-schaefer** [comment]
Agreed, those tests involving interface embedding don't look right.

Also, we need to talk to IT to upgrade Jenkins to Go 1.14 before we merge this. (I can do that.)

**Comment by sauyon** [comment]
[Dist-compare](https://git.semmle.com/sauyon/dist-compare-reports/tree/profiling-sauyon-lee.northeurope.cloudapp.azure.com_1582882309070) looks clean, with a slight slowdown.

**Comment by max-schaefer** [comment]
Nice, looks like the build for source-to-image got fixed?

IT is working on upgrading Jenkins, once they confirm that it's ready we can merge this.

**Comment by sauyon** [comment]
> Nice, looks like the build for source-to-image got fixed?

Just double checked the logs and it looks like the Go frontend is now correctly swallowing cgo errors (again?) :tada:.

**Comment by max-schaefer** [comment]
Jenkins has been upgraded. On second thought, though, we also need to upgrade things on LGTM.com, so I'll delay merging this until after the next distribution upgrade has been kicked off on Monday.

**Comment by sauyon** [comment]
It looks like these errors are related to #41. It seems like embedded methods are treated as a single method, and so there are database inconsistencies and it's leading to some strange results.

**Comment by sauyon** [comment]
Does this mean we should add information about embedded types to interfaces as well, and then build methods in QL?

Or do you think we should just make the method column not unique in method hosts and then work around that in QL?

**Comment by max-schaefer** [comment]
Ugh, making that column unique was just an oversight. I'll get that fixed asap.

**Comment by max-schaefer** [comment]
See https://github.com/github/codeql-go/pull/44.

**Comment by max-schaefer** [comment]
Needs conflict resolution.

**Comment by sauyon** [comment]
I think that should do it.

**Comment by max-schaefer** [comment]
Thanks; I'm still waiting for IT to work out some kinks in the upgrade on our infrastructure, then we can test this.

**Comment by max-schaefer** [comment]
The upgrade is done; I'll set off a job to verify that everything plays together nicely, and if it does I'll merge.

**Comment by max-schaefer** [comment]
Ah, actually, I just noticed that the tests aren't passing on a merge of this branch and master due to an interaction between this PR and https://github.com/github/codeql-go/pull/61. The new results look reasonable; I'll make a PR against your branch.

(As an aside, it's a little sad that our CI didn't catch this for us. I think goci would have rerun the tests when master changed, but apparently our current Actions setup doesn't.)

**Comment by sauyon** [comment]
I can fix the tests. I'll look into fixing that with actions.

**Comment by max-schaefer** [comment]
> I'll make a PR against your branch

https://github.com/sauyon/codeql-go/pull/3

**Comment by max-schaefer** [comment]
All looking good; merging.

**Comment by max-schaefer** [comment]
This should have had a change note. (Not flagging up that omission was my fault as the reviewer, but I would really appreciate it if you could help out by more proactively adding change notes to your PRs.)

**Comment by sauyon** [comment]
Ah, I'll make a PR for one, and will do. Generally all changes noticable by a user should have one, right?

**Comment by max-schaefer** [comment]
Correct, that is our usual standard.

**Pull request merged**
