### PR TITLE
Merge `rc/3.5` branch into `main`

### PR DESCRIPTION
**Pull request by edoardopirovano**
Merges the `rc/3.5` branch back into `main`. This merges cleanly so nothing of much note here.

@dbartol @aeisenberg As in the `github/codeql` PR, I've taken the liberty of doing a minor version bump of the Go packs here since this is the end of a GHES release.

### CODE REVIEW

**Comment by dbartol** [comment]
I pushed a commit to update the version of the dependency on `suite-helpers` to match the bump on that pack's definition in the `codeql` repo.

**Review by dbartol — APPROVED** [review]
LGTM

**Comment by edoardopirovano** [comment]
> I pushed a commit to update the version of the dependency on `suite-helpers` to match the bump on that pack's definition in the `codeql` repo.

Thanks. Is it okay to depend on that version here even if it hasn't been released yet?

**Comment by dbartol** [comment]
> Thanks. Is it okay to depend on that version here even if it hasn't been released yet?

Oh, right. No, it isn't. I'll revert.

**Pull request merged**
