### PR TITLE
Fix performance issue with `package`

### PR DESCRIPTION
**Pull request by sauyon**
(Hopefully, dist-compare started)

### CODE REVIEW

**Comment by sauyon** [comment]
For some reason `EvanphxJsonPatch` is failing; I'm going to go to sleep now so if somebody wants to figure that one out and push that feel free.

**Review by smowton — APPROVED** [review]

**Comment by owen-mc** [comment]
@sauyon I looked into and made a PR to fix the problem (which I introduced in the first place). Merge this PR and then rebase: https://github.com/github/codeql-go/pull/495.

**Review by owen-mc — APPROVED** [review]
I love that we can remove `bindingset[result]` from all the `packagepath()` predicates

**Comment by smowton** [comment]
I notice this landed on rc/3.1, but comments in #lgtm-distribution suggest we've missed the boat for 3.1. Never mind; 3.2 will have a 5% performance improvement for large databases now :)

**Comment by smowton** [comment]
(but we should fix up the branches -- reset rc/3.1 to before this merge and take this directly into `main` probably, to reduce confusion re: what actually got released)

**Pull request merged**
