### PR TITLE
Add taint tracking for the compress/* packages

### PR DESCRIPTION
**Pull request by gagliardetto**
Part of #167

### CODE REVIEW

**Comment by gagliardetto** [comment]
Given that there still are other 22 PRs to go, which group of packages do you suggest to do next? (So that higher-priority packages are done first)

See the list here: https://github.com/github/codeql-go/pull/167#issuecomment-654071379

**Comment by gagliardetto** [comment]
Or I'll just continue with the progression.

**Comment by max-schaefer** [comment]
> which group of packages do you suggest to do next?

Ideally something that is security relevant, but I don't have any more concrete suggestion than that.

**Comment by max-schaefer** [comment]
Performance evaluation came back fine, so merging.

**Pull request merged**
