### PR TITLE
Add new module path for beego and xmlpath

### PR DESCRIPTION
**Pull request by owen-mc**
Beego moved from astaxie/beego to beego/beego on 13 Dec 2020. The
old location still works but is not being updated.

### CODE REVIEW

**Comment by owen-mc** [comment]
I found another module path for `xmlpath` which I've added, and a few other miscellaneous clean-ups.

**Review by sauyon — APPROVED** [review]
LGTM

**Comment by owen-mc** [comment]
Do you think I should do a dist-compare or LGTM run?

**Comment by sauyon** [comment]
Seems safe enough, let's just let the dist-upgrade process deal with issues if they occur.

**Pull request merged**
