### PR TITLE
Expand Taint-Tracking to include 67 std-lib packages (with tests)

### PR DESCRIPTION
**Pull request by gagliardetto**
### Summary

- This PR adds taint-tracking for many standard Go library packages for which (in my opinion) it makes sense to have taint tracking (I erred on the side of abundance).
- Each taint-track was manually decided. CodeQL and golang code were generated from those decisions.
- Each taint-tracked element has its own test scenario with golang code ( see https://github.com/gagliardetto/codeql-go/tree/taint-stdlib-a/ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow )
- The taint-tracking modules (one module per package, one package per file) are in  https://github.com/gagliardetto/codeql-go/tree/taint-stdlib-a/ql/src/semmle/go/frameworks/stdlib

### The Taint-Tracking Classes

- For each std lib package, there is one file that contains the module and classes dedicated to the taint-tracking for that package.
- Right now, the codeql classes are in their most human-friendly form (very easily readable); if performance requires it, they can be compressed (ugly-fied) in some very efficient ways.

### The Golang Test Code

- For each taint-tracking class, there is a simulation of that scenario in a Golang function.
- I wrote a [custom testing query](https://github.com/gagliardetto/codeql-go/blob/taint-stdlib-a/ql/test/library-tests/semmle/go/frameworks/StdlibTaintFlow/StdlibTaintFlow.ql) to simplify my life and be able to visually inspect the results in vscode thanks to the CodeQL extension that highlights taint-tracking elements.

### TODO

- [ ] Any other library you consider worth including?
- [x] I'm still working on some more libraries taint-tracking, that should be added this week.
- [ ] Remove duplicates from https://github.com/github/codeql-go/blob/master/ql/src/semmle/go/frameworks/Stdlib.qll and also make sure I did not **miss** any taint-tracking currently implemented there.
- [ ] Establish a standardized directory and file hierarchy and logic.
- [ ] Right now, all of the taint-tracking modules are imported inside https://github.com/github/codeql-go/blob/master/ql/src/semmle/go/frameworks/Stdlib.qll (with `import semmle.go.frameworks.stdlib.ImportAll`), but the imports could be made more selective, deciding case by case.
- [x] Compress (uglify) classes.

### The Standard Library (from list available at https://godoc.org/-/go; see also https://golang.org/pkg/)

Go version: go version go1.14.1 linux/amd64

NOTE: ignored all `internal` and `vendor` packages.

Each item in the list is a package on its own; those that have a [x] are the ones that have been tracked and have tests. 

- [x] `archive/tar`
- [x] `archive/zip`
- [x] `bufio`
- [ ] `builtin`
- [x] `bytes`
- [ ] `cmd/api`
- [ ] `cmd/asm`
- [ ] `cmd/buildid`
- [ ] `cmd/cgo`
- [ ] `cmd/compile`
- [ ] `cmd/cover`
- [ ] `cmd/dist`
- [ ] `cmd/doc`
- [ ] `cmd/fix`
- [ ] `cmd/go`
- [ ] `cmd/gofmt`
- [ ] `cmd/link`
- [ ] `cmd/nm`
- [ ] `cmd/objdump`
- [ ] `cmd/pack`
- [ ] `cmd/pprof`
- [ ] `cmd/test2json`
- [ ] `cmd/trace`
- [ ] `cmd/vet`
- [x] `compress/bzip2`
- [x] `compress/flate`
- [x] `compress/gzip`
- [x] `compress/lzw`
- [x] `compress/zlib`
- [x] `container/heap`
- [x] `container/list`
- [x] `container/ring`
- [x] `context`
- [x] `crypto`
- [ ] `crypto/aes`
- [x] `crypto/cipher`
- [ ] `crypto/des`
- [ ] `crypto/dsa`
- [x] `crypto/ecdsa`
- [x] `crypto/ed25519`
- [ ] `crypto/elliptic`
- [ ] `crypto/hmac`
- [ ] `crypto/md5`
- [ ] `crypto/rand`
- [ ] `crypto/rc4`
- [x] `crypto/rsa`
- [ ] `crypto/sha1`
- [ ] `crypto/sha256`
- [ ] `crypto/sha512`
- [ ] `crypto/subtle`
- [x] `crypto/tls`
- [x] `crypto/x509`
- [ ] `crypto/x509/pkix`
- [x] `database/sql`
- [x] `database/sql/driver`
- [ ] `debug/dwarf`
- [ ] `debug/elf`
- [ ] `debug/gosym`
- [ ] `debug/macho`
- [ ] `debug/pe`
- [ ] `debug/plan9obj`
- [x] `encoding`
- [x] `encoding/ascii85`
- [x] `encoding/asn1`
- [x] `encoding/base32`
- [x] `encoding/base64`
- [x] `encoding/binary`
- [x] `encoding/csv`
- [x] `encoding/gob`
- [x] `encoding/hex`
- [x] `encoding/json`
- [x] `encoding/pem`
- [x] `encoding/xml`
- [x] `errors`
- [x] `expvar`
- [ ] `flag`
- [x] `fmt`
- [ ] `go/ast`
- [ ] `go/build`
- [ ] `go/constant`
- [ ] `go/doc`
- [ ] `go/format`
- [ ] `go/importer`
- [ ] `go/parser`
- [ ] `go/printer`
- [ ] `go/scanner`
- [ ] `go/token`
- [ ] `go/types`
- [ ] `hash`
- [ ] `hash/adler32`
- [ ] `hash/crc32`
- [ ] `hash/crc64`
- [ ] `hash/fnv`
- [ ] `hash/maphash`
- [x] `html`
- [x] `html/template`
- [ ] `image`
- [ ] `image/color`
- [ ] `image/color/palette`
- [ ] `image/draw`
- [ ] `image/gif`
- [ ] `image/jpeg`
- [ ] `image/png`
- [ ] `index/suffixarray`
- [x] `io`
- [x] `io/ioutil`
- [x] `log`
- [ ] `log/syslog`
- [ ] `math`
- [ ] `math/big`
- [ ] `math/bits`
- [ ] `math/cmplx`
- [ ] `math/rand`
- [x] `mime`
- [x] `mime/multipart`
- [x] `mime/quotedprintable`
- [x] `net`
- [x] `net/http`
- [ ] `net/http/cgi`
- [ ] `net/http/cookiejar`
- [ ] `net/http/fcgi`
- [ ] `net/http/httptest`
- [ ] `net/http/httptrace`
- [x] `net/http/httputil`
- [ ] `net/http/pprof`
- [x] `net/mail`
- [ ] `net/rpc`
- [ ] `net/rpc/jsonrpc`
- [ ] `net/smtp`
- [x] `net/textproto`
- [x] `net/url`
- [x] `os`
- [ ] `os/exec`
- [ ] `os/signal`
- [ ] `os/user`
- [x] `path`
- [x] `path/filepath`
- [ ] `plugin`
- [x] `reflect`
- [x] `regexp`
- [ ] `regexp/syntax`
- [ ] `runtime`
- [ ] `runtime/cgo`
- [ ] `runtime/debug`
- [ ] `runtime/pprof`
- [ ] `runtime/race`
- [ ] `runtime/trace`
- [x] `sort`
- [x] `strconv`
- [x] `strings`
- [x] `sync`
- [x] `sync/atomic`
- [x] `syscall`
- [ ] `syscall/js`
- [ ] `testing`
- [ ] `testing/iotest`
- [ ] `testing/quick`
- [x] `text/scanner`
- [x] `text/tabwriter`
- [x] `text/template`
- [ ] `text/template/parse`
- [ ] `time`
- [x] `unicode`
- [x] `unicode/utf16`
- [x] `unicode/utf8`
- [ ] `unsafe`

### CODE REVIEW

**Comment by gagliardetto** [comment]
This PR is ready for review.

### NOTES:

1. I will add packages from `golang.org/x/` in another PR.
2. Removed (most) taint-tracking duplicates from https://github.com/github/codeql-go/blob/master/ql/src/semmle/go/frameworks/Stdlib.qll without compromising existing functionality.
3. The `mac` build failed at the `unzip codeql` step; will trigger it again.

**Comment by gagliardetto** [comment]
To reduce the number of classes, this is my initial idea for simplifying (uglyfying) the generated codeql classes:


### Functions (if only funcs)

```codeql
  private string getAFuncNameForClassNameHere() {
    // signature: Foo(string) (string)
    result = "Foo"
    or
    // signature: Bar(string) (string, error)
    result = "Bar"
    or
    // signature: Baz(string) (string, int)
    result = "Baz"
  }

  class ClassNameHere extends TaintTracking::FunctionModel {
    ClassNameHere() { hasQualifiedName("package", getAFuncNameForClassNameHere()) }

    override predicate hasTaintFlow(DataFlow::FunctionInput inp, DataFlow::FunctionOutput outp) {
      inp.isParameter(0) and outp.isResult()
    }
  }
```

### Methods (if only methods)

```codeql
  class ClassNameHere extends TaintTracking::FunctionModel, Method {
    ClassNameHere() {
      exists(Method m |
        // signature: (*ObjectName0) MethodNameFoo() (string)
        m.hasQualifiedName("package", "ObjectName12", "MethodNameFoo")
        or
        // signature: (*ObjectName17) MethodNameBar() (string)
        m.hasQualifiedName("package", "ObjectName17", "MethodNameBar")
        or
        // signature: (*ObjectName22) MethodNameBaz() (string)
        m.hasQualifiedName("package", "ObjectName22", "MethodNameBaz")
      |
        this.(Method) = m
      )
    }

    override predicate hasTaintFlow(FunctionInput inp, FunctionOutput outp) {
      inp.isReceiver() and outp.isResult()
    }
  }
```


### Interfaces (if only interfaces)

```codeql
  private class ClassNameHere extends TaintTracking::FunctionModel, Method {
    ClassNameHere() {
      // signature: func (InterfaceName0) MethodNameFoo(string)
      implements("package", "InterfaceName0", "MethodNameFoo")
      or
      // signature: func (InterfaceName1) MethodNameBar(string)
      implements("package", "InterfaceName1", "MethodNameBar")
      or
      // signature: func (InterfaceName1) MethodNameBaz(string)
      implements("package", "InterfaceName1", "MethodNameBaz")
    }

    override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
      input.isReceiver() and output.isParameter(0)
    }
  }
```

### Mixed (for that extra savings in number of classes)

```codeql
  private string getAFuncNameForClassNameHere() {
    // signature: Foo(string) (string)
    result = "Foo"
    or
    // signature: Bar(string) (string, error)
    result = "Bar"
    or
    // signature: Baz(string) (string, int)
    result = "Baz"
  }

  private class ClassNameHere extends TaintTracking::FunctionModel, Method {
    ClassNameHere() {
      hasQualifiedName("package", getAFuncNameForClassNameHere())
      or
      exists(Method m |
        // signature: (*ObjectName0) MethodNameFoo() (string)
        m.hasQualifiedName("package", "ObjectName12", "MethodNameFoo")
        or
        // signature: (*ObjectName17) MethodNameBar() (string)
        m.hasQualifiedName("package", "ObjectName17", "MethodNameBar")
        or
        // signature: (*ObjectName22) MethodNameBaz() (string)
        m.hasQualifiedName("package", "ObjectName22", "MethodNameBaz")
      |
        this.(Method) = m
      )
      or
      (
        // signature: func (InterfaceName0) MethodNameFoo(string)
        implements("package", "InterfaceName0", "MethodNameFoo")
        or
        // signature: func (InterfaceName1) MethodNameBar(string)
        implements("package", "InterfaceName1", "MethodNameBar")
        or
        // signature: func (InterfaceName1) MethodNameBaz(string)
        implements("package", "InterfaceName1", "MethodNameBaz")
      )
    }

    override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
      input.isReceiver() and output.isParameter(0)
    }
  }
```

**Comment by max-schaefer** [comment]
This looks like a good way forward. You could consider, for instance, having one class per package that you model.

Can you explain the motivation for having the extra `getAFuncNameForClassNameHere` predicate? Couldn't you just inline that into the characteristic predicate?

Also, I assume that in generall you'll need different function inputs and outputs for different functions. Perhaps the easiest way to handle that would be to introduce fields:

```ql
private class PkgModel extends TaintTracking::FunctionModel {
  FunctionInput i;
  FunctionOutput o;

  SomkPkgModel() {
    this.hasQualifiedName("pkg", "f") and i.isParameter(0) and o.isResult()
    or
    this.hasQualifiedName("pkg", "g") and i.isReceiver() and o.isParameter(0)
  }

  override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
    input = i and output = o
  }
}
```

(Finally, note that in your example for the mixed case you don't want to extend `Method`, otherwise you can't model plain functions with that class.)

**Comment by max-schaefer** [comment]
Thanks again for your work on this! We will try to get it reviewed as soon as possible, but due to the sheer size of this PR it may take a while.

**Comment by gagliardetto** [comment]
> ```ql
> private class PkgModel extends TaintTracking::FunctionModel {
>   FunctionInput i;
>   FunctionOutput o;
> 
>   SomkPkgModel() {
>     this.hasQualifiedName("pkg", "f") and i.isParameter(0) and o.isResult()
>     or
>     this.hasQualifiedName("pkg", "g") and i.isReceiver() and o.isParameter(0)
>   }
> 
>   override predicate hasTaintFlow(FunctionInput input, FunctionOutput output) {
>     input = i and output = o
>   }
> }
> ```

This looks definitely nice. I will get this implemented next week.

> Can you explain the motivation for having the extra getAFuncNameForClassNameHere predicate? Couldn't you just inline that into the characteristic predicate?

It's just the habit; my brain still thinks `inlining = bad`.

> Thanks again for your work on this! We will try to get it reviewed as soon as possible, but due to the sheer size of this PR it may take a while.

Please let me know if you need any clarification, or want to have access to the tool I used to create the codeql and golang code.

**Comment by gagliardetto** [comment]
I regenerated the codeql code with a new "template", and reduced the number of classes.

Now, for each package, there are (at most) two classes: one for taint-tracking functions, and one for methods/interfaces.

**Comment by gagliardetto** [comment]
Here's what the tool looks like:

tool_screenshot

I will open-source it after I'll have some time to refactor the backend code.

@sauyon @max-schaefer

**Comment by max-schaefer** [comment]
Oh, wow, that's quite something! Thanks for sharing and I look forward to seeing your tool open sourced.

**Comment by gagliardetto** [comment]
@max-schaefer @sauyon You can find the tool at https://github.com/gagliardetto/codebox

Still need to refactor it, tough.

**Comment by max-schaefer** [comment]
@gagliardetto, thanks again for your contribution and for your patience in bearing with us as we try to figure out how to review this.

I ran an internal evaluation of these changes, and unfortunately they seem to cause a large number of regressions, both in terms of performance and of results. I am pretty sure that your changes aren't themselves to blame for this, it is much more likely that they just happen to trigger or exacerbate existing problems in our library or other parts of the analysis.

However, given the volume of changes it will be very hard to pin down exactly what is causing the regressions. Is there an easy way of splitting up this pull request into smaller chunks that could be reviewed and evaluated in isolation?

**Comment by gagliardetto** [comment]
How about a PR for each package or group of similar/related packages?

**Comment by max-schaefer** [comment]
That would be fantastic!

**Comment by gagliardetto** [comment]
# Workflow:

### PR: standard-lib-pt-0

- [ ] Taint-track methods: Read, ReadAt, Write, WriteAt

### PR: standard-lib-pt-1

- [ ] archive/tar
- [ ] archive/zip

### PR: standard-lib-pt-2

- [ ] bufio
- [ ] bytes

### PR: standard-lib-pt-3

- [ ] compress/bzip2
- [ ] compress/flate
- [ ] compress/gzip
- [ ] compress/lzw
- [ ] compress/zlib

### PR: standard-lib-pt-4

- [ ] container/heap
- [ ] container/list
- [ ] container/ring

### PR: standard-lib-pt-5

- [ ] context

### PR: standard-lib-pt-6

- [ ] crypto
- [ ] crypto/cipher
- [ ] crypto/ecdsa
- [ ] crypto/ed25519
- [ ] crypto/rsa
- [ ] crypto/tls
- [ ] crypto/x509

### PR: standard-lib-pt-7

- [ ] database/sql
- [ ] database/sql/driver

### PR: standard-lib-pt-8

- [ ] encoding
- [ ] encoding/ascii85
- [ ] encoding/asn1
- [ ] encoding/base32
- [ ] encoding/base64
- [ ] encoding/binary
- [ ] encoding/csv
- [ ] encoding/gob
- [ ] encoding/hex
- [ ] encoding/json
- [ ] encoding/pem
- [ ] encoding/xml

### PR: standard-lib-pt-9

- [ ] errors
- [ ] expvar

### PR: standard-lib-pt-10

- [ ] fmt

### PR: standard-lib-pt-11

- [ ] html
- [ ] html/template

### PR: standard-lib-pt-12

- [ ] io
- [ ] io/ioutil

### PR: standard-lib-pt-13

- [ ] log

### PR: standard-lib-pt-14

- [ ] mime
- [ ] mime/multipart
- [ ] mime/quotedprintable

### PR: standard-lib-pt-15

- [ ] net
- [ ] net/http
- [ ] net/http/httputil
- [ ] net/mail
- [ ] net/textproto
- [ ] net/url

### PR: standard-lib-pt-16

- [ ] os

### PR: standard-lib-pt-17

- [ ] path
- [ ] path/filepath

### PR: standard-lib-pt-18

- [ ] reflect

### PR: standard-lib-pt-19

- [ ] regexp

### PR: standard-lib-pt-20

- [ ] sort

### PR: standard-lib-pt-21

- [ ] strconv
- [ ] strings

### PR: standard-lib-pt-22

- [ ] sync
- [ ] sync/atomic

### PR: standard-lib-pt-23

- [ ] syscall

### PR: standard-lib-pt-24

- [ ] text/scanner
- [ ] text/tabwriter
- [ ] text/template

### PR: standard-lib-pt-25

- [ ] unicode
- [ ] unicode/utf16
- [ ] unicode/utf8

### PR: standard-lib-pt-26

- [ ] Remove duplicates from https://github.com/github/codeql-go/blob/master/ql/src/semmle/go/frameworks/Stdlib.qll and also make sure I did not miss any taint-tracking currently implemented there.
- [ ] Add Marshaling-related classes to https://github.com/github/codeql-go/blob/master/ql/src/semmle/go/frameworks/Stdlib.qll

**Comment by gagliardetto** [comment]
What do you think?

**Comment by gagliardetto** [comment]
In addition to reviewing taint-tracking for each package, you'll also need to evaluate whether taint-tracking for some of the functions (or whole packages) is needed at all.

**Comment by max-schaefer** [comment]
Looks good, thanks!

**Comment by gagliardetto** [comment]
All PRs merged. Closing.

**Pull request closed without merging**
