### PR TITLE
go-extractor: support env-specified build flags

### PR DESCRIPTION
**Pull request by smowton**
See https://github.com/github/dsp-codeql/issues/47#issuecomment-664735656

### CODE REVIEW

**Comment by sauyon** [comment]
I thought this was handled by `GOFLAGS`, does that not work? Maybe it makes sense to have our own environment variable, though.

If `GOFLAGS` does work we might also want to document that it does.

**Comment by smowton** [comment]
Aha, that does work, so up to you whether you prefer one specifically targeting the config object passed to the packages.Load method, or one that will affect other go commands (e.g. those run from a Makefile)

**Comment by max-schaefer** [comment]
Oh, right, I had forgotten about `GOFLAGS`. We've actually previously told people to set that instead.

@smowton, when you say "that does work", do you mean it solves the problem that originally triggered this work? If so, then I'd be in favour of just going with `GOFLAGS` rather than having our own specialised version of it.

**Comment by smowton** [comment]
Yes, setting it appears to solve the problem linked at the top

**Comment by max-schaefer** [comment]
Right; then I'd say no need to implement our own flag yet. If we later find that we need it for something else, we can always resurrect this PR.

**Comment by smowton** [comment]
OK

**Comment by MAHDTech** [comment]
Thanks all!

I didn't realize the standard Golang environment variables were able to be used so that's good to know.

I have confirmed the original issue is fixed by setting the `GOFLAGS` and tested it successfully with Code Scanning on GHEC.

```yaml
# <snip>
env:
    GOFLAGS: -tags=dev
```

**Pull request closed without merging**
