### PR TITLE
Add consistency query flagging tests with unexpected frontend errors

### PR DESCRIPTION
**Pull request by max-schaefer**
CodeQL does not support consistency queries yet, but I have verified that it works as expected with `odasa qltest`.

### CODE REVIEW

**Comment by max-schaefer** [comment]
@sauyon, could I ask you to look into the Windows test failure? I think it's probably because we aren't normalising paths properly when extracting frontend diagnostic information, but I can't quite work it out in my head. Maybe it's easier if you look at an actual database built on Windows.

**Comment by sauyon** [comment]
Oddly enough, I tried running the tests on Windows and they passed.

I'll keep experimenting to try to reproduce the actions environment.

**Comment by sauyon** [comment]
Ah, I figured out my error (had some Java install issues and my build hadn't actually been successful...).

The `Error` in question seems not to have a file associated with it; it's `RawPosition` is `D:\Documents\codeql\go\ql\test\consistency\test.go:7:1`, but if I run

```codeql
import go

from Error e, string filepath
where e.hasLocationInfo(filepath, _, _, _, _)
select e.getRawPosition()
```

I get the empty string as the result.

**Comment by sauyon** [comment]
Should I try to write a fix for this?

**Comment by sauyon** [comment]
> I get the empty string as the result.

Sorry, I left the wrong select in there, it should be `select filepath`.

**Comment by max-schaefer** [comment]
> Should I try to write a fix for this?

Yes, please. This needs to be fixed in the extractor, the file path shouldn't be empty.

**Comment by max-schaefer** [comment]
Ugh, I know what it is, hang on a few minutes...

**Comment by max-schaefer** [comment]
Well, that only took 15 attempts.

**Pull request merged**
