### PR TITLE
Extract methods when they don't exist

### PR DESCRIPTION
**Pull request by sauyon**
I noticed Kubernetes was constantly complaining there was no label for methods, which seems strange, given that the underlying type *should* have been extracted already. I'm looking into why this is the case, but for now it seems like it's a good idea to just extract the method if its label doesn't exist.

### CODE REVIEW

**Comment by max-schaefer** [comment]
That fix looks a little dangerous to me. The warning message is there because I had assumed that this shouldn't happen, and I'd like to understand a little better why it does. I'll look into it.

**Comment by max-schaefer** [comment]
Also, I'm pretty sure those methods will get extracted eventually anyway, when their enclosing interface type is extracted.

**Comment by sauyon** [comment]
> Also, I'm pretty sure those methods will get extracted eventually anyway, when their enclosing interface type is extracted.

I think that if the label already exists, it won't actually do the extraction.

I think I've figured this one out, though: when the interface type is first encountered, it tries to extract the receiver type of its methods. This is done because the receiver type of an interface method can be the named type.

At this point, the extractor starts extracting the named type, and then attempts to get the method labels of the underlying type, which has not yet fully extracted.

**Comment by max-schaefer** [comment]
Ah, that sounds very plausible. But in that case won't the method get extracted once it's done extracting the named type and gets back to extracting the interface?

**Comment by sauyon** [comment]
I don't believe so, because there's a `!exists` check around the method object extraction in `extractType`, and the `MethodID` function will create the label.

**Comment by max-schaefer** [comment]
Ah, that's an excellent point. In that case I agree with your proposed solution, but let's do an evaluation.

**Comment by max-schaefer** [comment]
Also, for the evaluation, could you run with `--no-cleanup` and do consistency checks on the resulting databases?

**Comment by sauyon** [comment]
Will do.

**Comment by max-schaefer** [comment]
I ran a distribution build on live and that looked happy, so if the dist-compare looks reasonable as well I'll be happy to merge.

**Comment by sauyon** [comment]
It seems like the dist-compare machine ran out of space with only the one run, so I'll run it locally.

Is there more state than just the `working` directory?

**Comment by max-schaefer** [comment]
> Is there more state than just the working directory?

No

**Comment by max-schaefer** [comment]
> so I'll run it locally

Any word on this? The bug being fixed here is potentially quite a big problem, so I'd like to get it merged as soon as possible.

**Comment by sauyon** [comment]
> Any word on this? The bug being fixed here is potentially quite a big problem, so I'd like to get it merged as soon as possible.

This change removes a lot of database errors, but there's still an invalid key error in `cadvisor`. I'm not sure when that was introduced.

**Comment by sauyon** [comment]
After some digging, I figured out and fixed the issue (for `cadvisor`, at least); the underlying type was being used instead of the named type as the method label, which in this case meant that there were two methods with the same label, because there were two named types with the same underlying interface type.

I tried replacing the `extractMethod` call with the warning again, but it seems my explanation above still holds.

**Comment by max-schaefer** [comment]
Great!

> I tried replacing the extractMethod call with the warning again, but it seems my explanation above still holds.

I don't understand what that means.

**Comment by sauyon** [comment]
> I don't understand what that means.

Basically that the first commit is still necessary.

**Comment by max-schaefer** [comment]
Oh, sure, I totally agree with that.

With your latest fixes applied, what's the situation regarding database inconsistencies on `default.slugs`?

**Comment by sauyon** [comment]
I started a dist-compare, but I forgot to inhibit idling. Results should come soon, but hopefully this shouldn't have caused any more inconsistencies.

**Comment by sauyon** [comment]
I managed to run the evaluation on the wrong branch, which means this will probably have to wait until tomorrow, apologies.

**Comment by sauyon** [comment]
[Dist-compare](https://git.semmle.com/gist/sauyon/ee25e25683a180e56760759b216e10e6) clean, and we're back at 0 database inconsistency errors :tada:

**Comment by max-schaefer** [comment]
Brilliant, thanks for your work on this!

**Pull request merged**
