### PR TITLE
Update dependencies and clean go.mod

### PR DESCRIPTION
**Pull request by sauyon**

### CODE REVIEW

**Comment by smowton** [comment]
Looks good, but this one I'll definitely hold off til after the release considering golang.org/x/tools has had flaky release in the past :)

**Comment by sauyon** [comment]
Seems sensible, I'll run a dist-compare just in case.

**Comment by smowton** [comment]
Does the distcompare look ok?

**Comment by sauyon** [comment]
It failed because I failed to set up my machine properly...

**Comment by sauyon** [comment]
21 projects previously building have failed, though most of them seem like network errors.

kubernetes and terraformer were both killed, presumably by the OOM killer. It might be worth just enabling build tracing for those projects now.

**Comment by smowton** [comment]
Verified they were indeed ok -- lots of TCP timeouts and such, presumably transient network problems affecting a small minority of builds.

**Review by smowton — APPROVED** [review]

**Pull request merged**
