### PR TITLE
Add web framework: github.com/gofiber/fiber

### PR DESCRIPTION
**Pull request by gagliardetto**
Part of https://github.com/github/securitylab/issues/335

### Packages:

 - [github.com/gofiber/fiber@v1.14.6](https://pkg.go.dev/github.com/gofiber/fiber#v1.14.6)
 - [github.com/gofiber/utils@v0.1.0](https://pkg.go.dev/github.com/gofiber/utils#v0.1.0)

### Model kind `TaintTracking`:
  - `FUNCS`:
    - [func github.com/gofiber/fiber.NewError(code int, message ...string) *github.com/gofiber/fiber.Error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#NewError)
    - [func github.com/gofiber/utils.GetBytes(s string) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#GetBytes)
    - [func github.com/gofiber/utils.GetString(b []byte) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#GetString)
    - [func github.com/gofiber/utils.ImmutableString(s string) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#ImmutableString)
    - [func github.com/gofiber/utils.SafeBytes(b []byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#SafeBytes)
    - [func github.com/gofiber/utils.SafeString(s string) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#SafeString)
    - [func github.com/gofiber/utils.ToLower(b string) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#ToLower)
    - [func github.com/gofiber/utils.ToLowerBytes(b []byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#ToLowerBytes)
    - [func github.com/gofiber/utils.ToUpper(b string) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#ToUpper)
    - [func github.com/gofiber/utils.ToUpperBytes(b []byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#ToUpperBytes)
    - [func github.com/gofiber/utils.Trim(s string, cutset byte) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#Trim)
    - [func github.com/gofiber/utils.TrimBytes(b []byte, cutset byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#TrimBytes)
    - [func github.com/gofiber/utils.TrimLeft(s string, cutset byte) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#TrimLeft)
    - [func github.com/gofiber/utils.TrimLeftBytes(b []byte, cutset byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#TrimLeftBytes)
    - [func github.com/gofiber/utils.TrimRight(s string, cutset byte) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#TrimRight)
    - [func github.com/gofiber/utils.TrimRightBytes(b []byte, cutset byte) []byte](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#TrimRightBytes)
    - [func github.com/gofiber/utils.UnsafeBytes(s string) (bs []byte)](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#UnsafeBytes)
    - [func github.com/gofiber/utils.UnsafeString(b []byte) string](https://pkg.go.dev/github.com/gofiber/utils@v0.1.0#UnsafeString)

---

### Model kind `HTTP::Redirect`:
  - `FUNCS`:
    - [func (*github.com/gofiber/fiber.Ctx).Redirect(location string, status ...int)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Redirect)

---

### Model kind `HTTP::HeaderWrite`:
  - `FUNCS`:
    - [func (*github.com/gofiber/fiber.Ctx).Append(field string, values ...string)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Append)
    - [func (*github.com/gofiber/fiber.Ctx).Set(key string, val string)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Set)

---

### Model kind `HTTP::ResponseBody`:
  - `FUNCS`:
    - [func (*github.com/gofiber/fiber.Ctx).Format(body interface{})](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Format)
    - [func (*github.com/gofiber/fiber.Ctx).JSON(data interface{}) error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.JSON)
    - [func (*github.com/gofiber/fiber.Ctx).JSONP(data interface{}, callback ...string) error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.JSONP)
    - [func (*github.com/gofiber/fiber.Ctx).Send(bodies ...interface{})](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Send)
    - [func (*github.com/gofiber/fiber.Ctx).SendBytes(body []byte)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.SendBytes)
    - [func (*github.com/gofiber/fiber.Ctx).SendStream(stream io.Reader, size ...int)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.SendStream)
    - [func (*github.com/gofiber/fiber.Ctx).SendString(body string)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.SendString)
    - [func (*github.com/gofiber/fiber.Ctx).Write(bodies ...interface{})](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Write)

---

### Model kind `UntrustedFlowSource`:
  - `FUNCS`:
    - [func (*github.com/gofiber/fiber.Ctx).BaseURL() string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.BaseURL)
    - [func (*github.com/gofiber/fiber.Ctx).Body() string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Body)
    - [func (*github.com/gofiber/fiber.Ctx).BodyParser(out interface{}) error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.BodyParser)
    - [func (*github.com/gofiber/fiber.Ctx).Cookies(key string, defaultValue ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Cookies)
    - [func (*github.com/gofiber/fiber.Ctx).FormFile(key string) (*mime/multipart.FileHeader, error)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.FormFile)
    - [func (*github.com/gofiber/fiber.Ctx).FormValue(key string) (value string)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.FormValue)
    - [func (*github.com/gofiber/fiber.Ctx).Get(key string, defaultValue ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Get)
    - [func (*github.com/gofiber/fiber.Ctx).Hostname() string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Hostname)
    - [func (*github.com/gofiber/fiber.Ctx).Method(override ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Method)
    - [func (*github.com/gofiber/fiber.Ctx).MultipartForm() (*mime/multipart.Form, error)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.MultipartForm)
    - [func (*github.com/gofiber/fiber.Ctx).OriginalURL() string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.OriginalURL)
    - [func (*github.com/gofiber/fiber.Ctx).Params(key string, defaultValue ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Params)
    - [func (*github.com/gofiber/fiber.Ctx).Path(override ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Path)
    - [func (*github.com/gofiber/fiber.Ctx).Protocol() string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Protocol)
    - [func (*github.com/gofiber/fiber.Ctx).Query(key string, defaultValue ...string) string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Query)
    - [func (*github.com/gofiber/fiber.Ctx).QueryParser(out interface{}) error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.QueryParser)
    - [func (*github.com/gofiber/fiber.Ctx).Range(size int) (rangeData github.com/gofiber/fiber.Range, err error)](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Range)
    - [func (*github.com/gofiber/fiber.Ctx).Subdomains(offset ...int) []string](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Ctx.Subdomains)
  - `STRUCTS`:
    - [github.com/gofiber/fiber.Cookie](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Cookie)
    - [github.com/gofiber/fiber.Error](https://pkg.go.dev/github.com/gofiber/fiber@v1.14.6#Error)

### CODE REVIEW

**Comment by sauyon** [comment]
I think these are fine to go into non-experimental. Also, I think we should save the spec files for these somewhere in case we want to regenerate them for some reason. @smowton do you know if there's a problem with including them inside `ql/src`?

**Comment by smowton** [comment]
Similar to the FastHTTP PR, `Protocol` is very likely safe because the framework will have determined it is `http` or `https` by the time your code is reached.

Before we make this non-experimental we should evaluate the results on all projects -- @sauyon would you mind kicking off XSS and OpenRedirect restricted to the sinks/sources specified in this package and see what we get? Same goes for FastHTTP.

**Comment by gagliardetto** [comment]
> I think we should save the spec files for these somewhere in case we want to regenerate them for some reason.

Should I include the spec in each PR?

**Comment by sauyon** [comment]
Yes, I think it would make sense to have.

**Comment by gagliardetto** [comment]
I added the specs.

To use them, run:

```bash
make run-linux spec=/path/to/codemill-specs/web-frameworks/FastHTTP.json dir=generated http=true gen=true
```
or

```bash
GOPACKAGESDEBUG=true GO111MODULE=on GOOS=linux GOARCH=amd64 go run main.go --spec=/path/to/codemill-specs/web-frameworks/FastHTTP.json --dir=generated --http=true --gen=true --summary=true
```

or a variation of that.

**Comment by gagliardetto** [comment]
> Before we make this non-experimental we should evaluate the results on all projects -- @sauyon would you mind kicking off XSS and OpenRedirect restricted to the sinks/sources specified in this package and see what we get? Same goes for FastHTTP.

Any news on that front?

**Comment by gagliardetto** [comment]
Hey, any news here?

**Comment by sauyon** [comment]
Stuck in limbo waiting for a change to LGTM which may or may not happen.

On that note: are you intending to make the changes that `@smowton` recommended?

**Comment by gagliardetto** [comment]
> On that note: are you intending to make the changes that @smowton recommended?

Are the suggested changes necessary for the LGTM compare?

For the time being (if those changes aren't immediately necessary) I'll stand by and wait to have some clarity about the next steps in the evolution of the bug bounty program :thinking: 

This "little" project is taking waaay much longer to complete that I expected :cold_sweat:

**Comment by sauyon** [comment]
The LGTM runs looks fine to me; let me know if you'd prefer that we finished up these frameworks ourselves.

**Comment by gagliardetto** [comment]
> let me know if you'd prefer that we finished up these frameworks ourselves.

I'd like to wait a few more weeks before jumping ship.

**Comment by smowton** [comment]
It think if you address the comment

> Similar to the FastHTTP PR, `Protocol` is very likely safe because the framework will have determined it is http or https by the time your code is reached.

Then this is likely good to go

**Comment by gagliardetto** [comment]
Awesome! I'll fix that today

**Comment by gagliardetto** [comment]
> Similar to the FastHTTP PR, Protocol is very likely safe because the framework will have determined it is http or https by the time your code is reached.

The `protocol` is just syntactic sugar **for the client** (so that it knows what to use to connect to the server).

A client can specify any protocol and the server will accept it because it doesn't.

Example:

Server:

```go
package main

import (
	"fmt"
	"log"

	"github.com/valyala/fasthttp"
)

func main() {
	listenAddr := "127.0.0.1:8087"

	requestHandler := func(ctx *fasthttp.RequestCtx) {
		fmt.Fprintf(ctx, "Request protocol is %q", ctx.Request.Header.Protocol())
	}

	if err := fasthttp.ListenAndServe(listenAddr, requestHandler); err != nil {
		log.Fatalf("error in ListenAndServe: %s", err)
	}
}
```

and let's send a request with the `DONUT/123` protocol:

```bash
printf "HELLO whatever DONUT/123\r\n\r\n" | nc 127.0.0.1 8087
```
which outputs:

image

As for the argument "Everyone uses a load balancer in front of their services", I could assume that about any vulnerability and mitigation.

**Comment by gagliardetto** [comment]
Should be OK now. @smowton @sauyon

**Review by smowton — APPROVED** [review]

**Comment by gagliardetto** [comment]
:partying_face: :confetti_ball:

**Pull request merged**
