### PR TITLE
Move `strconv` and `strings` packages' taint-tracking to stdlib, and expand them

### PR DESCRIPTION
**Pull request by gagliardetto**
Part of #167 

`codebox` commands:

```bash
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/strconv --http
codebox --out-dir=./generated/latest --pkg=/usr/local/go/src/strings --http
```

### CODE REVIEW

**Comment by gagliardetto** [comment]
Should I use a regex for function name matching for similar functions, or it does not make any difference from a performance standpoint?

**Comment by smowton** [comment]
Personally I like that the particular functions are enumerated rather than using a glob that expresses intent but may hit things it doesn't intend to. 

Looks like the second commit, while described as just a move, actually adds support for at least NewReader, causing the test failures seen; suggest changing its commit message to fully describe what it's doing.

Finally I'm surprised to see this doesn't change StdlibTaintFlow.expected -- is that expected?

**Comment by gagliardetto** [comment]
> Finally I'm surprised to see this doesn't change StdlibTaintFlow.expected -- is that expected?

FFR: see https://github.com/github/codeql-go/pull/317#issuecomment-685672502

**Comment by smowton** [comment]
@max-schaefer I think the rune comment is applied; I'm going to make a derived PR that introduces the sanitiser for `Header.get("authorization").Split(":")[0]`, otherwise this lgtm

**Comment by smowton** [comment]
Rebased and derived here: https://github.com/github/codeql-go/pull/330

**Comment by max-schaefer** [comment]
Superseded by https://github.com/github/codeql-go/pull/330.

**Pull request closed without merging**
