### PR TITLE
Add integer overflow detection support for codeql-go.

### PR DESCRIPTION
**Pull request by singleghost**
I wrote a ql library which can perform range analysis on expression and
can detect whether an arithmetic operation may overflow. I wrote this library with reference to the `SimpleRangeAnalysis.qll` for C language. I hope this helps a little bit for those who want to detect integer overflow issues in code.

### CODE REVIEW

**Comment by max-schaefer** [comment]
Many thanks for your contribution, we really appreciate it!

Perhaps your library and query would be good candidates for inclusion in our new category of experimental CodeQL queries and libraries.

Would you mind taking a look at the [contribution guidelines](https://github.com/github/codeql-go/blob/master/ql/docs/experimental.md) for experimental queries and updating your pull request accordingly?

In particular:

  - the query and libraries should be under `ql/src/experimental`
  - the query needs an `@id` and a `@problem.severity`; also, its `select` clause currently is missing an alert message
  - all QL files need to be [autoformatted](https://help.semmle.com/codeql/codeql-for-vscode/reference/editor.html#autoformatting).

**Comment by singleghost** [comment]
Thank you for your feedback! I will reopen a new pull request to the experiment folder.

**Comment by max-schaefer** [comment]
No need to make a new pull request, you can just add commits to this one.

**Comment by singleghost** [comment]
Understood, I have added the new commit below this pull request.

**Pull request merged**
